
raw = [{'result_type': 'tips', 'data': []}, {'result_type': 'brand_ad', 'data': []},
       {'result_type': 'esports', 'data': []}, {
           'result_type': 'activity', 'data': []},
       {'result_type': 'web_game', 'data': []}, {
           'result_type': 'card', 'data': []},
       {'result_type': 'media_bangumi', 'data': []}, {
           'result_type': 'media_ft', 'data': []},
       {'result_type': 'bili_user', 'data': []}, {
           'result_type': 'user', 'data': []},
       {'result_type': 'star', 'data': []}, {'result_type': 'video', 'data': [
           {'type': 'video', 'id': 1002416941, 'author': '超想敲代码', 'mid': 272222941, 'typeid': '231',
            'typename': '计算机技术', 'arcurl': 'http://www.bilibili.com/video/av1002416941', 'aid': 1002416941,
            'bvid': 'BV1Cx4y1m7Gd',
            'title': '部署微调<em class="keyword">ChatGlm3</em>-<em class="keyword">6B大模型</em>【小白0到1】',
            'description': '手把手教学如何部署ChatGlm3大模型、使用LlaMa-Factory进行大模型微调。0代码部署、微调大模型，白嫖服务器，小白也能听得懂学得会！！！\n笔记链接：http://t.csdnimg.cn/ifaH5',
            'arcrank': '0', 'pic': '//i0.hdslb.com/bfs/archive/f6c02cb1b5be59e34275567e448ec9966184bd8a.jpg',
            'play': 21236, 'video_review': 25, 'favorites': 1039,
            'tag': '训练,AI,NLP,小白教程,大模型,chatglm,大模型微调,大模型部署,llama factory,loar微调', 'review': 533,
            'pubdate': 1711558909, 'senddate': 1712046485, 'duration': '40:20', 'badgepay': False,
            'hit_columns': ['title', 'description', 'author', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
            'rec_tags': None, 'new_rec_tags': [], 'rank_score': 172217254, 'like': 384,
            'upic': 'https://i1.hdslb.com/bfs/face/8e2e7246d8104ff3dbb29cbc783d6a4a5e41f53c.jpg', 'corner': '',
            'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 25, 'biz_data': None, 'is_charge_video': 0,
            'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
            'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
            'live_time': '', 'online': 0, 'rank_index': 1, 'rank_offset': 1, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
            'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
            'watched_show': None},
           {'type': 'video', 'id': 241845815, 'author': '木羽Cheney', 'mid': 3537113897241540, 'typeid': '209',
               'typename': '职业职场', 'arcurl': 'http://www.bilibili.com/video/av241845815', 'aid': 241845815,
               'bvid': 'BV1ce411J7nZ',
               'title': '【保姆级教程】6小时掌握开源<em class="keyword">大模型</em>本地部署到微调，从硬件指南到<em class="keyword">ChatGLM3</em>-<em class="keyword">6B模型</em>部署微调实战｜逐帧详解｜直达技术底层',
               'description': '公开课节选自付费课程《大模型技术实战课》，2024最新版2期课程现已上线！6大主流大模型+14项大模型工具+5大热门方向企业级实战项目，零基础直达大模型企业级应用！【付费课程信息】添加+🌏：littlecat_1207，回复“大模型”详询哦～',
               'arcrank': '0', 'pic': '//i0.hdslb.com/bfs/archive/a8a96d67fd033ad35b3699108be2e8b6cf25087e.png',
               'play': 144936, 'video_review': 1453, 'favorites': 9939,
               'tag': '模型,人工智能,AI,部署,微调,深度学习,OpenAI,本地部署,大语言模型 (LLM),ChatGLM3', 'review': 2581,
               'pubdate': 1706355351, 'senddate': 1710933841, 'duration': '384:41', 'badgepay': False,
               'hit_columns': ['title', 'description', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 115116645, 'like': 3150,
               'upic': 'https://i0.hdslb.com/bfs/face/6ef695686f04ea4b81846c64a507607d1fea8a89.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 1453, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 2, 'rank_offset': 2, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 1753100101, 'author': '编程分享录', 'mid': 674558378, 'typeid': '231',
               'typename': '计算机技术', 'arcurl': 'http://www.bilibili.com/video/av1753100101', 'aid': 1753100101,
               'bvid': 'BV1yx421m7tn',
               'title': '【<em class="keyword">大模型</em>微调】<em class="keyword">ChatGLM3</em>-<em class="keyword">6b大模型</em>微调 | 基于开源的<em class="keyword">大模型</em>的微调 | 使用自己的数据集来微调<em class="keyword">大模型</em> | 垂直领域<em class="keyword">大模型</em> | lora微调<em class="keyword">大模型</em>',
               'description': '【大模型微调】ChatGLM3-6b大模型微调 | 基于开源的大模型的微调 | 使用自己的数据集来微调大模型 | 垂直领域大模型 | lora微调大模型\n本视频中使用的是开源的大模型ChatGLM3，微调脚本为官方提供\n数据集可以自己制作，然后微调成垂直领域的大模型\n更多内容欢迎关注我',
               'arcrank': '0', 'pic': '//i2.hdslb.com/bfs/archive/ef58b014e4849f04f0d3ca10e963fe081e8e8a88.jpg', 'play': 5044,
               'video_review': 1, 'favorites': 375,
               'tag': '微调,大模型,lora,LLM,ChatGPT,大语言模型 (LLM),lora微调大模型,本地专有大模型', 'review': 62,
               'pubdate': 1712979794, 'senddate': 1712979794, 'duration': '32:1', 'badgepay': False,
               'hit_columns': ['title', 'description', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 111602141, 'like': 122,
               'upic': 'https://i2.hdslb.com/bfs/face/bdba0b71b2f4302c2086283d86e9bd13e95cfa74.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 1, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 3, 'rank_offset': 3, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 401497353, 'author': 'ChatGLM', 'mid': 3493270982232856, 'typeid': '231',
               'typename': '计算机技术', 'arcurl': 'http://www.bilibili.com/video/av401497353', 'aid': 401497353,
               'bvid': 'BV1fd4y1Z7Y5',
               'title': '【官方教程】<em class="keyword">ChatGLM</em>-<em class="keyword">6B</em> 微调：P-Tuning，LoRA，Full parameter',
               'description': '我们详细介绍了GLM的技术背景，以及ChatGLM-6B的微调方案，包括P-tuning、LoRA、Full-Parameter等，并针对提问提供了详细的回复。\n\n报告文件下载链接: https://pan.baidu.com/s/1CKS5yBz6-GN_J7UB_wxguw?pwd=g26m 提取码: g26m',
               'arcrank': '0', 'pic': '//i0.hdslb.com/bfs/archive/2cda769b22475cd6497d09aca1cd0cc3f3d19944.jpg',
               'play': 114165, 'video_review': 255, 'favorites': 8854,
               'tag': '教程,官方,清华,经验分享,大模型,科技猎手2023,chatglm,这就是AIGC,智谱AI', 'review': 362,
               'pubdate': 1684735924, 'senddate': 1684898768, 'duration': '78:45', 'badgepay': False,
               'hit_columns': ['title', 'description', 'author', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 105799013, 'like': 3406,
               'upic': 'https://i1.hdslb.com/bfs/face/ed1c8faa182cd66788af5b988d78570bdcee0780.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 255, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 4, 'rank_offset': 4, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 827358365, 'author': '九天Hector', 'mid': 385842994, 'typeid': '122',
               'typename': '野生技能协会', 'arcurl': 'http://www.bilibili.com/video/av827358365', 'aid': 827358365,
               'bvid': 'BV1Xg4y1N7kM',
               'title': '【入门】开源<em class="keyword">大模型</em>生态与<em class="keyword">ChatGLM</em>-<em class="keyword">6B大模型</em>介绍｜最强中文<em class="keyword">大模型</em>GLM介绍｜LLM开源<em class="keyword">大模型</em>概览',
               'description': '大模型入门系列教程第二弹：《开源大模型生态与ChatGLM-6B大模型介绍》来啦～视频将为大家详细介绍目前开源大模型生态，并重点介绍目前中文领域最强大模型GLM的技术生态，包括GLM-130B、ChatGLM-6B、visualGLM等，帮助大家快速建立技术认知，领跑大模型时代～\n公开课资料领取：添加客服VX：littlecat_1207，回复“LLM”即可免费领取哦～\n公开课视频节选自《大模型与AIGC技术实战》课程，完整版课为付费课程，课程包含提示工程技术、AIGC实战、大模型部署与API调用方法、L',
               'arcrank': '0', 'pic': '//i1.hdslb.com/bfs/archive/4907f2a28044d0d36e9a90a8ae18746145d6ac98.jpg',
               'play': 17723, 'video_review': 83, 'favorites': 637,
               'tag': '人工智能,机器学习,深度学习,OpenAI,GPT,GLM,LLM,ChatGPT,大语言模型,ChatGLM', 'review': 8,
               'pubdate': 1686822234, 'senddate': 1686828099, 'duration': '33:35', 'badgepay': False,
               'hit_columns': ['title', 'description', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 104681013, 'like': 575,
               'upic': 'https://i1.hdslb.com/bfs/face/667a093664817884057caa9c057cd16a91cde202.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 83, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 5, 'rank_offset': 5, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 238452117, 'author': '木羽Cheney', 'mid': 3537113897241540, 'typeid': '209',
               'typename': '职业职场', 'arcurl': 'http://www.bilibili.com/video/av238452117', 'aid': 238452117,
               'bvid': 'BV1je411U7Cv',
               'title': '<em class="keyword">ChatGLM3</em>-<em class="keyword">6B模型</em>本地部署必备！零门槛Ubuntu系统初始化配置教程|逐步带你完成配置|为<em class="keyword">大模型</em>运行打下基础！',
               'description': '想本地部署学习ChatGLM3-6B？本系列视频详细讲解了ChatGLM3-6B开源大模型的本地部署流程、Ubuntu系统初始化、大模型运行环境配置指南、以及五种运行方式等内容，除此之外我还给大家准备了34页超详细文档和课件，领取方式见置顶评论~',
               'arcrank': '0', 'pic': '//i0.hdslb.com/bfs/archive/92a499760ae300831af02324bf0d71f0960a999f.jpg', 'play': 5153,
               'video_review': 38, 'favorites': 258,
               'tag': '科技,人工智能,机器学习,深度学习,计算机技术,OpenAI,大模型,Agent,大语言模型 (LLM),ChatGLM3',
               'review': 68, 'pubdate': 1704710950, 'senddate': 1707005590, 'duration': '23:34', 'badgepay': False,
               'hit_columns': ['title', 'description', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 104542239, 'like': 78,
               'upic': 'https://i0.hdslb.com/bfs/face/6ef695686f04ea4b81846c64a507607d1fea8a89.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 38, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 6, 'rank_offset': 6, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 407925945, 'author': 'AI技术大本营', 'mid': 688174628, 'typeid': '230',
               'typename': '软件应用', 'arcurl': 'http://www.bilibili.com/video/av407925945', 'aid': 407925945,
               'bvid': 'BV1pG411X7XP',
               'title': '<em class="keyword">ChatGLM3</em>-<em class="keyword">6B大</em>语言<em class="keyword">模型</em>本地一键整合包下载地址',
               'description': 'ChatGLM3-6B的项目github地址：https://github.com/THUDM/ChatGLM3\nChatGLM3-6B大语言模型本地一键整合包下载地址：解压密码 www.aibl.vip\n 链接：https://pan.baidu.com/s/1zqOS_BkUbo8h7cXNxotypA?pwd=09n1 \n 提取码：09n1 \n整合包源下载地址：https://www.aibl.vip/thread-159-1-1.html',
               'arcrank': '0', 'pic': '//i1.hdslb.com/bfs/archive/92d691990f905b8a70f1961b20518c42fdb83e0c.jpg', 'play': 5982,
               'video_review': 2, 'favorites': 267, 'tag': '本地,语言模型,大语言模型,ChatGLM3,ChatGLM3-6B', 'review': 66,
               'pubdate': 1698893923, 'senddate': 1699366772, 'duration': '1:37', 'badgepay': False,
               'hit_columns': ['title', 'description', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 104078225, 'like': 111,
               'upic': 'https://i2.hdslb.com/bfs/face/608f762844b725e5a241212cb0b944bab0e5b8e9.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 2, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 7, 'rank_offset': 7, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 1551029013, 'author': '黑糖珍珠雲', 'mid': 10845739, 'typeid': '231',
               'typename': '计算机技术', 'arcurl': 'http://www.bilibili.com/video/av1551029013', 'aid': 1551029013,
               'bvid': 'BV1ky421z7GE',
               'title': '<em class="keyword">chatglm3</em>-<em class="keyword">6b</em>部署教程（胎教版）',
               'description': '还没来得及修改简介~', 'arcrank': '0',
               'pic': '//i0.hdslb.com/bfs/archive/bcd1135f15ecede08f2ed5b8cc36b97a98f20bf1.jpg', 'play': 2484,
               'video_review': 0, 'favorites': 143, 'tag': '教程,学习,深度学习,编程开发,语言模型', 'review': 86,
               'pubdate': 1708794985, 'senddate': 1709134531, 'duration': '47:28', 'badgepay': False,
               'hit_columns': ['title', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0, 'rec_tags': None,
               'new_rec_tags': [], 'rank_score': 103794296, 'like': 64,
               'upic': 'https://i1.hdslb.com/bfs/face/81561eadf554d2c0a9bcd84b77081801ae396de6.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 0, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 8, 'rank_offset': 8, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 708746434, 'author': '木羽Cheney', 'mid': 3537113897241540, 'typeid': '209',
               'typename': '职业职场', 'arcurl': 'http://www.bilibili.com/video/av708746434', 'aid': 708746434,
               'bvid': 'BV1uQ4y1L7PH',
               'title': '30分钟学会运行<em class="keyword">ChatGLM3</em>-<em class="keyword">6B模型</em>的P-Turning V2高效微调及全量微调代码',
               'description': '工作中急需微调Chat GLM3-6B模型，却不懂微调原理怎么办？这个视频中，即使大家对大模型微调的原理还不太了解，也能快速开始实际操作。我会帮助大家通俗的理解目前主流的高效微调方法并着重介绍如何快速运行ChatGLM3官方支持的P-Turning v2微调技术。此外，为了帮助大家更好地理解和实践这些技术，我还为大家准备了视频配套超详细的（34页）PDF文档，无套路，领取方式见置顶评论~',
               'arcrank': '0', 'pic': '//i1.hdslb.com/bfs/archive/8deb27023951be8181279d7a2ef7fe70f9cd25db.jpg', 'play': 8608,
               'video_review': 85, 'favorites': 642, 'tag': '高效,微调,大语言模型 (LLM),ChatGLM3', 'review': 228,
               'pubdate': 1705147200, 'senddate': 1705984805, 'duration': '37:2', 'badgepay': False,
               'hit_columns': ['title', 'description', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 103760272, 'like': 217,
               'upic': 'https://i0.hdslb.com/bfs/face/6ef695686f04ea4b81846c64a507607d1fea8a89.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 85, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 9, 'rank_offset': 9, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 747967526, 'author': 'ChatGLM', 'mid': 3493270982232856, 'typeid': '231',
               'typename': '计算机技术', 'arcurl': 'http://www.bilibili.com/video/av747967526', 'aid': 747967526,
               'bvid': 'BV1uC4y1J7yA',
               'title': '【官方教程】<em class="keyword">ChatGLM3</em>-<em class="keyword">6B</em> 部署和微调（Function Call、Code Interpreter、Agent）',
               'description': 'ChatGLM3 技术文档：https://zhipu-ai.feishu.cn/wiki/YInmwPmyii67VRkzU3BchPNzncg\n\n模型仓库：https://github.com/THUDM/ChatGLM3\n\n模型下载：\nHF：https://huggingface.co/THUDM\n魔搭：https://modelscope.cn/models/ZhipuAI\n\n文件下载：https://pan.baidu.com/s/14NtD9A3Ls3VkuIPy8Iar8Q?pwd=na5c',
               'arcrank': '0', 'pic': '//i1.hdslb.com/bfs/archive/0dbd4eb239aa469daea7913f4c60f0c8ef0bec88.jpg',
               'play': 102161, 'video_review': 182, 'favorites': 5953,
               'tag': '人工智能,清华大学,微调,大模型,agent,chatglm,智谱AI', 'review': 458, 'pubdate': 1698850951,
               'senddate': 1703912205, 'duration': '57:9', 'badgepay': False,
               'hit_columns': ['title', 'description', 'author', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 103651090, 'like': 2358,
               'upic': 'https://i1.hdslb.com/bfs/face/ed1c8faa182cd66788af5b988d78570bdcee0780.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 182, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 10, 'rank_offset': 10, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 113174787460517, 'author': '大模型入门教程', 'mid': 1569066411, 'typeid': '122',
               'typename': '野生技能协会', 'arcurl': 'http://www.bilibili.com/video/av113174787460517',
               'aid': 113174787460517, 'bvid': 'BV1J2tkeSEzK',
               'title': '<em class="keyword">ChatGLM</em>-<em class="keyword">6B模型</em>部署与微调教程，<em class="keyword">大模型</em>训练流程及原理+微调容易踩的坑全详解！从<em class="keyword">模型</em>架构到实际应用，（Function Call、Code Interpr',
               'description': '', 'arcrank': '0',
               'pic': '//i0.hdslb.com/bfs/archive/7c90b5806ecb9fe23923f2700b0dd2b9f084e473.jpg', 'play': 670,
               'video_review': 92, 'favorites': 51, 'tag': '模型,人工智能,AI,大模型,AI入门,大模型入门,大模型教程',
               'review': 19, 'pubdate': 1726910405, 'senddate': 1726910405, 'duration': '62:53', 'badgepay': False,
               'hit_columns': ['title', 'author', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0, 'rec_tags': None,
               'new_rec_tags': [], 'rank_score': 103603959, 'like': 18,
               'upic': 'https://i0.hdslb.com/bfs/face/260d2004cecc111a68fc2e6e5a2edd1ef273ce32.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 92, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 11, 'rank_offset': 11, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 1502084615, 'author': '紫陌垂杨洛西', 'mid': 107645594, 'typeid': '231',
               'typename': '计算机技术', 'arcurl': 'http://www.bilibili.com/video/av1502084615', 'aid': 1502084615,
               'bvid': 'BV1YD42177VE', 'title': '<em class="keyword">chatglm3模型</em>本地部署及微调',
               'description': '最新的chatglm3模型部署和llora微调，因为chatglm3官网代码有修改，记录下现在的模型微调和踩过的坑。',
               'arcrank': '0', 'pic': '//i1.hdslb.com/bfs/archive/de4a9555e97933992947e7acb9617ae04d897665.png', 'play': 4981,
               'video_review': 6, 'favorites': 309, 'tag': '微调,大模型,本地部署,lora微调,chagglm3', 'review': 87,
               'pubdate': 1711181772, 'senddate': 1712490535, 'duration': '30:45', 'badgepay': False,
               'hit_columns': ['title', 'description', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 103272500, 'like': 90,
               'upic': 'https://i2.hdslb.com/bfs/face/269f1f31c8842a4525957476a9f02bad77056f64.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 6, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 12, 'rank_offset': 12, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 113127978964818, 'author': '10年Java老兵转战大模型', 'mid': 1946337667, 'typeid': '231',
               'typename': '计算机技术', 'arcurl': 'http://www.bilibili.com/video/av113127978964818', 'aid': 113127978964818,
               'bvid': 'BV1jw4te8ETy',
               'title': 'AI<em class="keyword">大模型</em>-实战QLoRA微调<em class="keyword">ChatGLM3</em>-<em class="keyword">6B</em>',
               'description': '迪哥给大家整理了一份大模型学习资料包！\n包含：\n1.Transformer、BERT、Huggingface三大基础模型源码资料\n2.ChatGLM、LLM、LangChain、Lora等大语言模型预训练及微调教程和源码资料\n3.A2024最新大模型相关面试题\n4.大模型前沿论文',
               'arcrank': '0', 'pic': '//i1.hdslb.com/bfs/archive/b610233582e1e45ae8c8449ab38e057f42032a54.jpg', 'play': 1423,
               'video_review': 23, 'favorites': 39, 'tag': '教程,模型,学习,实战,人工智能,AI,课程,AGI,大模型,AI大模型',
               'review': 1, 'pubdate': 1726197608, 'senddate': 1728179707, 'duration': '152:49', 'badgepay': False,
               'hit_columns': ['title', 'description', 'author', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 103001871, 'like': 30,
               'upic': 'https://i1.hdslb.com/bfs/face/73f5c2df517b3c680f23ae4b6a5e1b7dc171cbed.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 23, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 13, 'rank_offset': 13, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 365368404, 'author': '会算法的猫', 'mid': 567541406, 'typeid': '21', 'typename': '日常',
               'arcurl': 'http://www.bilibili.com/video/av365368404', 'aid': 365368404, 'bvid': 'BV1X94y157Ko',
               'title': '<em class="keyword">大模型chatglm3</em>-<em class="keyword">6b</em>之开外挂',
               'description': '大模型agent', 'arcrank': '0',
               'pic': '//i1.hdslb.com/bfs/archive/54f6830cebdeec63f5debedf890216bad410d7c6.jpg', 'play': 4155,
               'video_review': 0, 'favorites': 184, 'tag': 'NLP,大模型,Agent,chatglm3', 'review': 20, 'pubdate': 1698676877,
               'senddate': 1698693121, 'duration': '9:7', 'badgepay': False, 'hit_columns': ['title', 'description', 'tag'],
               'view_type': '', 'is_pay': 0, 'is_union_video': 0, 'rec_tags': None, 'new_rec_tags': [],
               'rank_score': 102581309, 'like': 70,
               'upic': 'https://i2.hdslb.com/bfs/face/e686268636fb12b4a1b2877505b2c2b007ce8f06.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 0, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 14, 'rank_offset': 14, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 708387714, 'author': '木羽Cheney', 'mid': 3537113897241540, 'typeid': '209',
               'typename': '职业职场', 'arcurl': 'http://www.bilibili.com/video/av708387714', 'aid': 708387714,
               'bvid': 'BV1wQ4y1j7uT',
               'title': '5种运行<em class="keyword">ChatGLM3</em>-<em class="keyword">6B模型</em>的方式！<em class="keyword">大模型</em>本地部署必备|手把手领学，效率指数提升！',
               'description': '想本地部署学习ChatGLM3-6B？本系列视频详细讲解了ChatGLM3-6B开源大模型的本地部署流程、Ubuntu系统初始化、大模型运行环境配置指南、以及五种运行方式等内容，除此之外我还给大家准备了34页超详细文档和课件，领取方式见置顶评论~',
               'arcrank': '0', 'pic': '//i2.hdslb.com/bfs/archive/3c650ff25fba2ff9bd462d18f136c24433118f09.jpg', 'play': 2669,
               'video_review': 30, 'favorites': 66,
               'tag': '科技,人工智能,机器学习,深度学习,计算机技术,OpenAI,大模型,Agent,大语言模型 (LLM),ChatGLM3',
               'review': 12, 'pubdate': 1704802200, 'senddate': 1704802202, 'duration': '15:22', 'badgepay': False,
               'hit_columns': ['title', 'description', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 102155836, 'like': 28,
               'upic': 'https://i0.hdslb.com/bfs/face/6ef695686f04ea4b81846c64a507607d1fea8a89.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 30, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 15, 'rank_offset': 15, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 113201798711974, 'author': '大模型老于', 'mid': 3546755297708147, 'typeid': '231',
               'typename': '计算机技术', 'arcurl': 'http://www.bilibili.com/video/av113201798711974', 'aid': 113201798711974,
               'bvid': 'BV1TKxLeLE8W',
               'title': '【B站首推】2小时掌握<em class="keyword">ChatGLM</em>-4本地部署-微调-实战，原理讲解+代码解析，超详细，LLM_<em class="keyword">大模型</em>_微调_-Agent_RAG',
               'description': 'GLM4大模型教程来啦！深度介绍国产大模型天花板GLM4模型特性，零基础入门，高效掌握GLM4模型API调用方法',
               'arcrank': '0', 'pic': '//i1.hdslb.com/bfs/archive/e9255bee2a76ab9c11d47d65f256eac5ed18db3c.png', 'play': 7772,
               'video_review': 153, 'favorites': 261, 'tag': '模型,人工智能,AI,微调,GPT,大模型,GLM,openAI,模型部署,智普',
               'review': 50, 'pubdate': 1727340348, 'senddate': 1727340348, 'duration': '59:23', 'badgepay': False,
               'hit_columns': ['title', 'description', 'author', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 101928152, 'like': 173,
               'upic': 'https://i2.hdslb.com/bfs/face/845295f684f173997f0c812517084e61881c5e0a.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 153, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 16, 'rank_offset': 16, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 826984653, 'author': 'ChatGLM', 'mid': 3493270982232856, 'typeid': '231',
               'typename': '计算机技术', 'arcurl': 'http://www.bilibili.com/video/av826984653', 'aid': 826984653,
               'bvid': 'BV1iu4y1Z7bv',
               'title': '【报告】从GLM-130B到<em class="keyword">ChatGLM</em>：<em class="keyword">大模型</em>预训练与微调',
               'description': '本报告为GLM技术团队成员在「NLG专委会真知论坛（GenTalk第7期）」的报告分享，报告中详细讲述了GLM-130B预训练过程，以及ChatGLM开发过程，并提出了几点大模型开发心得。\n\n本论坛另有复旦大学MOSS团队成员孙天祥的相关报告，可参考：https://www.bilibili.com/video/BV1is4y1i7cZ',
               'arcrank': '0', 'pic': '//i0.hdslb.com/bfs/archive/d1df889d21c3da487c21930e10aea8a72a67b3c5.jpg',
               'play': 60841, 'video_review': 66, 'favorites': 3934, 'tag': '大模型,GLM,预训练,科技猎手2023,chatglm',
               'review': 156, 'pubdate': 1685807653, 'senddate': 1685823811, 'duration': '76:54', 'badgepay': False,
               'hit_columns': ['title', 'description', 'author', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 101780655, 'like': 1587,
               'upic': 'https://i1.hdslb.com/bfs/face/ed1c8faa182cd66788af5b988d78570bdcee0780.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 66, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 17, 'rank_offset': 17, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 1051768122, 'author': 'frontEndBugMaker', 'mid': 429914741, 'typeid': '231',
               'typename': '计算机技术', 'arcurl': 'http://www.bilibili.com/video/av1051768122', 'aid': 1051768122,
               'bvid': 'BV1UH4y1W7PH',
               'title': '【保姆级教程】使用<em class="keyword">ChatGLM3</em>-<em class="keyword">6B</em>＋oneAPI＋Fastgpt＋LLaMA-Factory实现本地<em class="keyword">大模型</em>微调＋知识库＋接口管理',
               'description': '使用了清华开源的大模型chatGLM3-6b进行本地部署，LLaMA-Factory进行大模型微调，使用fastgpt的知识库连接本地大模型，使用oneAPI进行接口管理。',
               'arcrank': '0', 'pic': '//i0.hdslb.com/bfs/archive/a348a89ce71340947aed7d06f88fc7f0a939f04e.jpg',
               'play': 14331, 'video_review': 8, 'favorites': 1158,
               'tag': '教程,模型,微调,编程开发,保姆级教程,知识库,本地搭建大模型', 'review': 175, 'pubdate': 1710672312,
               'senddate': 1710728461, 'duration': '74:19', 'badgepay': False, 'hit_columns': ['title', 'description', 'tag'],
               'view_type': '', 'is_pay': 0, 'is_union_video': 0, 'rec_tags': None, 'new_rec_tags': [],
               'rank_score': 101719297, 'like': 373,
               'upic': 'https://i2.hdslb.com/bfs/face/d3c13a4fbd1dfae11c054456d96314b63c83b0a7.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 8, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 18, 'rank_offset': 18, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 113049478432847, 'author': '吴恩达-机器学习', 'mid': 3546736138128063, 'typeid': '231',
               'typename': '计算机技术', 'arcurl': 'http://www.bilibili.com/video/av113049478432847', 'aid': 113049478432847,
               'bvid': 'BV15LH5e1EDQ',
               'title': '【保姆级教程】6小时掌握开源<em class="keyword">大模型</em>本地部署到微调，从硬件指南到<em class="keyword">ChatGLM3</em>-<em class="keyword">6B模型</em>部署微调实战，这应该是B站最好的<em class="keyword">大模型</em>教程了！',
               'description': '想领取超详细课件的伙伴，后台滴滴免费领取，更多与ChatGLM3及大模型相关的问题，欢迎评论区交流哦[打call]~',
               'arcrank': '0', 'pic': '//i1.hdslb.com/bfs/archive/14516528a708b212fc9d03759618ef3c9db4f933.png', 'play': 1410,
               'video_review': 21, 'favorites': 107,
               'tag': '人工智能,AI,科技是第一生产力,计算机视觉,深度学习,计算机技术,大模型,科技猎手,AIGC,大模型微调,大模型面试',
               'review': 1, 'pubdate': 1724998337, 'senddate': 1726630249, 'duration': '369:14', 'badgepay': False,
               'hit_columns': ['title', 'description', 'author', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 101687121, 'like': 23,
               'upic': 'https://i0.hdslb.com/bfs/face/86d6e918ae76c33dbbad2409ed442cb9aff3746b.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 21, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 19, 'rank_offset': 19, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None},
           {'type': 'video', 'id': 743207011, 'author': '人工智能与Python', 'mid': 1350253317, 'typeid': '231',
               'typename': '计算机技术', 'arcurl': 'http://www.bilibili.com/video/av743207011', 'aid': 743207011,
               'bvid': 'BV15k4y1P7N5',
               'title': '吹爆！全网最通俗易懂的<em class="keyword">ChatGLM</em>预训练+微调教程，北大博士后手把手带你调用属于自己的对话<em class="keyword">大模型</em>—<em class="keyword">ChatGLM</em>!',
               'description': '关注公众号：咕泡AI，回复：555\r\n即可获取课程资料及60G深度学习精选资料包！\r\n更有：AI公开课、论文指导、简历指导、竞赛指导、技术问题解答！\r\n1.上千篇CVPR、ICCV顶会论文\r\n2.动手学习深度学习、花书、西瓜书等AI必读书籍\r\n3.唐宇迪博士精心整理的人工智能学习大纲\r\n4.机器学习算法+深度学习神经网络基础教程\r\n5.OpenCV、Pytorch、YOLO等主流框架算法实战教程',
               'arcrank': '0', 'pic': '//i0.hdslb.com/bfs/archive/01903bb8df3eedfe57feef07e52849f35f1d77f5.png',
               'play': 10891, 'video_review': 47, 'favorites': 621,
               'tag': '人工智能,机器学习,深度学习,自然语言处理,大模型,多模态,ChatGLM-6B,ChatGLM微调,ChatGLM训练,ChatGLM部署',
               'review': 21, 'pubdate': 1688723464, 'senddate': 1688811833, 'duration': '178:50', 'badgepay': False,
               'hit_columns': ['title', 'description', 'tag'], 'view_type': '', 'is_pay': 0, 'is_union_video': 0,
               'rec_tags': None, 'new_rec_tags': [], 'rank_score': 101667211, 'like': 111,
               'upic': 'https://i0.hdslb.com/bfs/face/fad84c271423850eace9745a417f613b38fc2bbb.jpg', 'corner': '',
               'cover': '', 'desc': '', 'url': '', 'rec_reason': '', 'danmaku': 47, 'biz_data': None, 'is_charge_video': 0,
               'vt': 0, 'enable_vt': 0, 'vt_display': '', 'subtitle': '', 'episode_count_text': '', 'release_status': 0,
               'is_intervene': 0, 'area': 0, 'style': 0, 'cate_name': '', 'is_live_room_inline': 0, 'live_status': 0,
               'live_time': '', 'online': 0, 'rank_index': 20, 'rank_offset': 20, 'roomid': 0, 'short_id': 0, 'spread_id': 0,
               'tags': '', 'uface': '', 'uid': 0, 'uname': '', 'user_cover': '', 'parent_area_id': 0, 'parent_area_name': '',
               'watched_show': None}]}]

for result in raw:
    if result['data']:  # 检查data列表是否非空
        for item in result['data']:
            processed_data = [
                item.get('type', '未知类型'),
                item.get('author', '未知作者'),
                item.get('typename', '未知分类'),
                item.get('arcurl', '无链接'),
                item.get('title', '无标题').replace(
                    '<em class="keyword">', '').replace('</em>', ''),
                item.get('description', '无描述'),
                item.get('play', 0),
                item.get('video_review', 0),
                item.get('favorites', 0),
                item.get('comment', 0),
                # comments,
                # datetime.datetime.fromtimestamp(item.get('pubdate', 0)).strftime('%Y-%m-%d %H:%M:%S'),
            ]

            headers = ["类型", "作者", "分类", "视频链接", "标题", "描述", "播放量", "弹幕数", "收藏数", "标签",
                       "发布日期", "评论"]

            result_text = '\n'.join(
                f"{header}: {data}" for header, data in zip(headers, processed_data))

            print(result_text)
